# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 
google_analytics: 
title: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ByLuisEspinoza.co # top blog

description: Stylish Jekyll Theme
author:
  name: ByLuisEspinoza.co #the footer
  email: ing.espinozalj@gmail.com
  github: byluisespinoza
  twitter: byluisespinoza
  linkedin: byluisespinoza
  pinterest: 
  bio: Are you ready to turn your ideas into reality and build a wildly successful business? 
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
